# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

# container: ubuntu:18.04

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: |
    git submodule update --init --recursive
    pip install pytest-runner wheel
    python setup.py bdist_wheel
#    cd dds/src
#    cp Makefiles/Makefile_linux_shared ./Makefile
#    sed -i 's/^THREADING.*/THREADING       = $(THR_STL)/' Makefile
#    sed -i 's/^THREAD_COMPILE.*/THREAD_COMPILE  =/' Makefile
#    sed -i 's/^THREAD_LINK.*/THREAD_LINK     =/' Makefile
#    make
#    python --version

- task: CopyFiles@2
    inputs:
      contents: dist/**
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: redeal_basic_wheel